-- =====================================================================
-- Code Cademy — Supabase backend
-- Paste this whole file into Supabase → SQL Editor → New query → Run.
-- It is safe to run more than once: every statement is idempotent.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. Tables
-- ---------------------------------------------------------------------
create table if not exists public.profiles (
  id          uuid primary key references auth.users(id) on delete cascade,
  full_name   text not null default '',
  role        text not null default 'student',
  club        text,
  created_at  timestamptz not null default now()
);

create table if not exists public.materials (
  id           bigint generated by default as identity primary key,
  club         text not null,
  level        text not null,
  title        text not null,
  file_path    text not null,
  uploaded_by  uuid references public.profiles(id) on delete set null,
  created_at   timestamptz not null default now()
);

create table if not exists public.exam_questions (
  id          bigint generated by default as identity primary key,
  club        text not null,
  level       text not null,
  question    text not null,
  option_a    text not null,   -- always the correct answer
  option_b    text not null,
  option_c    text not null,
  option_d    text not null,
  created_by  uuid references public.profiles(id) on delete set null,
  created_at  timestamptz not null default now()
);

create table if not exists public.exam_attempts (
  id          bigint generated by default as identity primary key,
  student_id  uuid not null references public.profiles(id) on delete cascade,
  club        text not null,
  level       text not null,
  score       int  not null,
  passed      boolean not null,
  created_at  timestamptz not null default now()
);

create table if not exists public.progress (
  id          bigint generated by default as identity primary key,
  student_id  uuid not null references public.profiles(id) on delete cascade,
  status      text,
  note        text,
  created_at  timestamptz not null default now()
);

create table if not exists public.notifications (
  id          bigint generated by default as identity primary key,
  club        text,            -- null = every club
  title       text not null,
  body        text not null,
  created_by  uuid references public.profiles(id) on delete set null,
  created_at  timestamptz not null default now()
);

-- Older databases may have these tables without some of the columns the
-- website uses (e.g. "level" was added later). Add whatever is missing.
-- Existing books / questions without a level are put in the Beginner level.
alter table public.profiles       add column if not exists full_name  text not null default '';
alter table public.profiles       add column if not exists role       text not null default 'student';
alter table public.profiles       add column if not exists club       text;
alter table public.profiles       add column if not exists created_at timestamptz not null default now();

alter table public.materials      add column if not exists club        text;
alter table public.materials      add column if not exists level       text default 'Beginner (A1-A2)';
alter table public.materials      add column if not exists title       text;
alter table public.materials      add column if not exists file_path   text;
alter table public.materials      add column if not exists uploaded_by uuid;
alter table public.materials      add column if not exists created_at  timestamptz not null default now();
alter table public.materials      add column if not exists file_name   text;
alter table public.materials      add column if not exists file_size   bigint;
alter table public.materials      add column if not exists mime_type   text;

alter table public.exam_questions add column if not exists club       text;
alter table public.exam_questions add column if not exists level      text default 'Beginner (A1-A2)';
alter table public.exam_questions add column if not exists question   text;
alter table public.exam_questions add column if not exists option_a   text;
alter table public.exam_questions add column if not exists option_b   text;
alter table public.exam_questions add column if not exists option_c   text;
alter table public.exam_questions add column if not exists option_d   text;
alter table public.exam_questions add column if not exists created_by uuid;
alter table public.exam_questions add column if not exists created_at timestamptz not null default now();

alter table public.exam_attempts  add column if not exists student_id uuid;
alter table public.exam_attempts  add column if not exists club       text;
alter table public.exam_attempts  add column if not exists level      text;
alter table public.exam_attempts  add column if not exists score      int;
alter table public.exam_attempts  add column if not exists passed     boolean not null default false;
alter table public.exam_attempts  add column if not exists created_at timestamptz not null default now();

alter table public.progress       add column if not exists student_id uuid;
alter table public.progress       add column if not exists status     text;
alter table public.progress       add column if not exists note       text;
alter table public.progress       add column if not exists created_at timestamptz not null default now();

alter table public.notifications  add column if not exists club       text;
alter table public.notifications  add column if not exists title      text;
alter table public.notifications  add column if not exists body       text;
alter table public.notifications  add column if not exists created_by uuid;
alter table public.notifications  add column if not exists created_at timestamptz not null default now();

alter table public.profiles add column if not exists link_code text;   -- students share it with their parents
alter table public.profiles add column if not exists avatar_color text;
create unique index if not exists profiles_link_code_idx on public.profiles (link_code);
alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles add constraint profiles_role_check
  check (role in ('student','parent','teacher','admin')) not valid;

-- Parents ↔ children
create table if not exists public.parent_links (
  parent_id   uuid not null references public.profiles(id) on delete cascade,
  student_id  uuid not null references public.profiles(id) on delete cascade,
  created_at  timestamptz not null default now(),
  primary key (parent_id, student_id)
);

-- Chat: one conversation per student between the student, their parents and
-- the teachers. "private" messages are only visible to parents and teachers.
create table if not exists public.messages (
  id           bigint generated by default as identity primary key,
  student_id   uuid not null references public.profiles(id) on delete cascade,
  sender_id    uuid not null default auth.uid() references public.profiles(id) on delete cascade,
  sender_name  text,
  sender_role  text,
  body         text not null check (length(body) between 1 and 4000),
  private      boolean not null default false,
  created_at   timestamptz not null default now()
);
create index if not exists messages_student_idx on public.messages (student_id, created_at desc);

-- when each person last opened each conversation → unread counters
create table if not exists public.chat_reads (
  user_id      uuid not null references public.profiles(id) on delete cascade,
  student_id   uuid not null references public.profiles(id) on delete cascade,
  last_read_at timestamptz not null default now(),
  primary key (user_id, student_id)
);

-- NEW: every time a student opens a book we log it → streaks + leaderboard.
-- material_id gets the same type as materials.id (uuid or bigint, depending
-- on how the materials table was originally created).
do $$
declare v_type text;
begin
  select format_type(a.atttypid, a.atttypmod) into v_type
    from pg_attribute a
   where a.attrelid = 'public.materials'::regclass and a.attname = 'id';
  execute format($f$
    create table if not exists public.material_reads (
      id           bigint generated by default as identity primary key,
      student_id   uuid not null references public.profiles(id) on delete cascade,
      material_id  %s not null references public.materials(id) on delete cascade,
      club         text,
      read_on      date not null default current_date,
      created_at   timestamptz not null default now(),
      unique (student_id, material_id, read_on)
    )$f$, v_type);
end $$;

create index if not exists materials_club_level_idx on public.materials (club, level, created_at desc);
create index if not exists exam_q_club_level_idx    on public.exam_questions (club, level);
create index if not exists reads_student_idx        on public.material_reads (student_id, read_on desc);
create index if not exists reads_club_idx           on public.material_reads (club, read_on desc);

-- ---------------------------------------------------------------------
-- 2. Helpers
-- ---------------------------------------------------------------------
create or replace function public.is_teacher()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role in ('teacher','admin'));
$$;

create or replace function public.my_role()
returns text language sql stable security definer set search_path = public as $$
  select role from public.profiles where id = auth.uid();
$$;

create or replace function public.my_club()
returns text language sql stable security definer set search_path = public as $$
  select club from public.profiles where id = auth.uid();
$$;

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin');
$$;

create or replace function public.is_parent_of(p_student uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.parent_links where parent_id = auth.uid() and student_id = p_student);
$$;

-- clubs of the signed-in parent's children
create or replace function public.my_children_clubs()
returns setof text language sql stable security definer set search_path = public as $$
  select distinct p.club from public.parent_links l join public.profiles p on p.id = l.student_id
   where l.parent_id = auth.uid() and p.club is not null;
$$;

create or replace function public.new_link_code()
returns text language plpgsql volatile set search_path = public as $$
declare v text;
begin
  loop
    -- no 0/O/1/I so it is easy to read out over the phone
    v := (select string_agg(substr('ABCDEFGHJKLMNPQRSTUVWXYZ23456789', 1 + floor(random() * 32)::int, 1), '')
            from generate_series(1, 6));
    exit when not exists (select 1 from public.profiles where link_code = v);
  end loop;
  return v;
end $$;

create or replace function public.profiles_before_write()
returns trigger language plpgsql set search_path = public as $$
begin
  if new.role = 'student' and new.link_code is null then new.link_code := public.new_link_code(); end if;
  return new;
end $$;
drop trigger if exists profiles_before_write on public.profiles;
create trigger profiles_before_write before insert or update on public.profiles
  for each row execute function public.profiles_before_write();
update public.profiles set link_code = public.new_link_code() where role = 'student' and link_code is null;

-- Create the profile row automatically on sign-up (works even when
-- "Confirm email" is on and the browser has no session yet).
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, full_name, role, club)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', ''),
    -- teachers and admins are only ever promoted by an admin (set_user_role)
    case when new.raw_user_meta_data->>'role' = 'parent' then 'parent' else 'student' end,
    case when new.raw_user_meta_data->>'role' = 'parent' then null
         else nullif(new.raw_user_meta_data->>'club', '') end
  )
  on conflict (id) do nothing;
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------------
-- 3. Row Level Security
-- ---------------------------------------------------------------------
alter table public.profiles       enable row level security;
alter table public.materials      enable row level security;
alter table public.exam_questions enable row level security;
alter table public.exam_attempts  enable row level security;
alter table public.progress       enable row level security;
alter table public.notifications  enable row level security;
alter table public.material_reads enable row level security;
alter table public.parent_links   enable row level security;
alter table public.messages       enable row level security;
alter table public.chat_reads     enable row level security;

-- profiles
drop policy if exists "profiles: read own or teacher" on public.profiles;
create policy "profiles: read own or teacher" on public.profiles
  for select using (id = auth.uid() or public.is_teacher() or public.is_parent_of(id));
drop policy if exists "profiles: insert own" on public.profiles;
create policy "profiles: insert own" on public.profiles
  for insert with check (id = auth.uid() and role in ('student','parent'));
drop policy if exists "profiles: update own" on public.profiles;
create policy "profiles: update own" on public.profiles
  for update using (id = auth.uid())
  with check (id = auth.uid() and role = public.my_role());  -- nobody can promote themselves

-- materials
drop policy if exists "materials: read club or teacher" on public.materials;
create policy "materials: read club or teacher" on public.materials
  for select using (public.is_teacher() or club = public.my_club()
                    or club in (select public.my_children_clubs()));
drop policy if exists "materials: teacher insert" on public.materials;
create policy "materials: teacher insert" on public.materials
  for insert with check (public.is_teacher());
drop policy if exists "materials: teacher update" on public.materials;
create policy "materials: teacher update" on public.materials
  for update using (public.is_teacher());
drop policy if exists "materials: teacher delete" on public.materials;
create policy "materials: teacher delete" on public.materials
  for delete using (public.is_teacher());

-- exam questions: only teachers read them directly (students go through
-- get_exam(), which never reveals the correct answer)
drop policy if exists "exam_q: teacher all" on public.exam_questions;
create policy "exam_q: teacher all" on public.exam_questions
  for all using (public.is_teacher()) with check (public.is_teacher());

-- exam attempts: written only by submit_exam(); students read their own
drop policy if exists "attempts: read own or teacher" on public.exam_attempts;
create policy "attempts: read own or teacher" on public.exam_attempts
  for select using (student_id = auth.uid() or public.is_teacher() or public.is_parent_of(student_id));

-- progress
drop policy if exists "progress: read own or teacher" on public.progress;
create policy "progress: read own or teacher" on public.progress
  for select using (student_id = auth.uid() or public.is_teacher() or public.is_parent_of(student_id));
drop policy if exists "progress: teacher insert" on public.progress;
create policy "progress: teacher insert" on public.progress
  for insert with check (public.is_teacher());

-- notifications
drop policy if exists "notif: read" on public.notifications;
create policy "notif: read" on public.notifications
  for select using (public.is_teacher() or club is null or club = public.my_club()
                    or club in (select public.my_children_clubs()));
drop policy if exists "notif: teacher insert" on public.notifications;
create policy "notif: teacher insert" on public.notifications
  for insert with check (public.is_teacher());

-- material reads
drop policy if exists "reads: read own or teacher" on public.material_reads;
create policy "reads: read own or teacher" on public.material_reads
  for select using (student_id = auth.uid() or public.is_teacher() or public.is_parent_of(student_id));
drop policy if exists "reads: insert own" on public.material_reads;
create policy "reads: insert own" on public.material_reads
  for insert with check (student_id = auth.uid());

-- parent links: created only through link_child(); readable by both sides
drop policy if exists "links: read" on public.parent_links;
create policy "links: read" on public.parent_links
  for select using (parent_id = auth.uid() or student_id = auth.uid() or public.is_teacher());
drop policy if exists "links: parent unlink" on public.parent_links;
create policy "links: parent unlink" on public.parent_links
  for delete using (parent_id = auth.uid() or public.is_admin());

-- messages
drop policy if exists "messages: read" on public.messages;
create policy "messages: read" on public.messages
  for select using (public.is_teacher() or public.is_parent_of(student_id)
                    or (student_id = auth.uid() and not private));
drop policy if exists "messages: send" on public.messages;
create policy "messages: send" on public.messages
  for insert with check (sender_id = auth.uid() and (
    public.is_teacher() or public.is_parent_of(student_id) or (student_id = auth.uid() and not private)));
drop policy if exists "messages: delete own" on public.messages;
create policy "messages: delete own" on public.messages
  for delete using (sender_id = auth.uid() or public.is_admin());

drop policy if exists "chat_reads: own" on public.chat_reads;
create policy "chat_reads: own" on public.chat_reads
  for all using (user_id = auth.uid()) with check (user_id = auth.uid());

-- the sender's name / role are stamped by the server, never trusted from the browser
create or replace function public.messages_before_insert()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  new.sender_id := auth.uid();
  select full_name, role into new.sender_name, new.sender_role from public.profiles where id = auth.uid();
  new.created_at := now();
  return new;
end $$;
drop trigger if exists messages_before_insert on public.messages;
create trigger messages_before_insert before insert on public.messages
  for each row execute function public.messages_before_insert();

-- ---------------------------------------------------------------------
-- 4. Storage bucket for books & materials
-- ---------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit)
values ('materials', 'materials', true, 52428800)  -- 50 MB per file
on conflict (id) do update set public = true, file_size_limit = excluded.file_size_limit;

drop policy if exists "materials bucket: public read"    on storage.objects;
create policy "materials bucket: public read" on storage.objects
  for select using (bucket_id = 'materials');
drop policy if exists "materials bucket: teacher upload" on storage.objects;
create policy "materials bucket: teacher upload" on storage.objects
  for insert to authenticated with check (bucket_id = 'materials' and public.is_teacher());
drop policy if exists "materials bucket: teacher update" on storage.objects;
create policy "materials bucket: teacher update" on storage.objects
  for update to authenticated using (bucket_id = 'materials' and public.is_teacher());
drop policy if exists "materials bucket: teacher delete" on storage.objects;
create policy "materials bucket: teacher delete" on storage.objects
  for delete to authenticated using (bucket_id = 'materials' and public.is_teacher());

-- ---------------------------------------------------------------------
-- 5. Server-side API (RPC functions called from the website)
-- ---------------------------------------------------------------------

-- Exam questions for a student, options shuffled, correct answer hidden.
drop function if exists public.get_exam(text, text);
create or replace function public.get_exam(p_club text, p_level text)
returns table (id text, question text, options text[])
language sql volatile security definer set search_path = public as $$
  select q.id::text, q.question,
         (select array_agg(o order by random())
            from unnest(array[q.option_a, q.option_b, q.option_c, q.option_d]) as o)
    from public.exam_questions q
   where q.club = p_club and q.level = p_level
     and (public.is_teacher() or p_club = public.my_club())
   order by q.created_at;
$$;

-- Grades the exam on the server and records the attempt.
-- p_answers = {"<question id>": "<chosen option text>", ...}
create or replace function public.submit_exam(p_club text, p_level text, p_answers jsonb)
returns table (score int, passed boolean, correct int, total int)
language plpgsql security definer set search_path = public as $$
declare
  v_total int; v_correct int; v_score int; v_passed boolean;
begin
  if auth.uid() is null then raise exception 'Not signed in'; end if;
  if p_club is distinct from public.my_club() then raise exception 'This exam is not for your club'; end if;

  select count(*), count(*) filter (where p_answers->>(q.id::text) = q.option_a)
    into v_total, v_correct
    from public.exam_questions q
   where q.club = p_club and q.level = p_level;

  if v_total = 0 then raise exception 'No questions for this level yet'; end if;

  v_score  := round(v_correct * 100.0 / v_total);
  v_passed := v_score >= 70;

  insert into public.exam_attempts (student_id, club, level, score, passed)
  values (auth.uid(), p_club, p_level, v_score, v_passed);

  return query select v_score, v_passed, v_correct, v_total;
end $$;

-- Top readers of a club over the last N days (names only — no emails).
-- p_club = null → every club (teachers).
create or replace function public.club_leaderboard(p_club text default null, p_days int default 7)
returns table (student_id uuid, full_name text, club text, books bigint, days_active bigint)
language sql stable security definer set search_path = public as $$
  select r.student_id, p.full_name, p.club,
         count(distinct r.material_id) as books,
         count(distinct r.read_on)     as days_active
    from public.material_reads r
    join public.profiles p on p.id = r.student_id
   where r.read_on >= current_date - greatest(p_days, 1) + 1
     and (case when public.is_teacher() then (p_club is null or p.club = p_club)
               else p.club = public.my_club() end)
   group by r.student_id, p.full_name, p.club
   order by books desc, days_active desc, p.full_name
   limit 10;
$$;

-- Most opened books (teacher insight).
drop function if exists public.popular_materials(int);
create or replace function public.popular_materials(p_days int default 30)
returns table (material_id text, title text, club text, level text, readers bigint)
language sql stable security definer set search_path = public as $$
  select m.id::text, m.title, m.club, m.level, count(distinct r.student_id)
    from public.material_reads r
    join public.materials m on m.id = r.material_id
   where public.is_teacher()
     and r.read_on >= current_date - greatest(p_days, 1) + 1
   group by m.id
   order by 5 desc, m.title
   limit 5;
$$;

-- ----- admin: manage who is a teacher -----
create or replace function public.admin_list_users()
returns table (id uuid, full_name text, email text, role text, club text, created_at timestamptz)
language sql stable security definer set search_path = public as $$
  select p.id, p.full_name, u.email::text, p.role, p.club, p.created_at
    from public.profiles p join auth.users u on u.id = p.id
   where public.is_admin()
   order by p.created_at desc;
$$;

create or replace function public.set_user_role(p_user uuid, p_role text, p_club text default null)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not public.is_admin() then raise exception 'Only an admin can change roles'; end if;
  if p_role not in ('student','parent','teacher','admin') then raise exception 'Unknown role %', p_role; end if;
  if p_user = auth.uid() and p_role <> 'admin' then raise exception 'You cannot remove your own admin access'; end if;
  update public.profiles
     set role = p_role,
         club = case when p_role = 'student' then coalesce(p_club, club) else club end
   where id = p_user;
end $$;

-- ----- parents -----
create or replace function public.link_child(p_code text)
returns table (student_id uuid, full_name text, club text)
language plpgsql security definer set search_path = public as $$
declare v_student public.profiles%rowtype;
begin
  if public.my_role() <> 'parent' then raise exception 'Only parent accounts can link a child'; end if;
  select * into v_student from public.profiles
   where link_code = upper(trim(p_code)) and role = 'student';
  if not found then raise exception 'No student found with this code'; end if;
  insert into public.parent_links (parent_id, student_id) values (auth.uid(), v_student.id)
  on conflict do nothing;
  return query select v_student.id, v_student.full_name, v_student.club;
end $$;

-- everything a parent (or teacher) needs to follow one student
create or replace function public.student_report(p_student uuid)
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare v jsonb;
begin
  if not (public.is_teacher() or public.is_parent_of(p_student) or p_student = auth.uid()) then
    raise exception 'Not allowed';
  end if;
  select jsonb_build_object(
    'student',   (select jsonb_build_object('id', id, 'full_name', full_name, 'club', club) from public.profiles where id = p_student),
    'books_week',(select count(distinct material_id) from public.material_reads where student_id = p_student and read_on > current_date - 7),
    'books_total',(select count(distinct material_id) from public.material_reads where student_id = p_student),
    'read_days', (select coalesce(jsonb_agg(d order by d desc), '[]') from (select distinct read_on d from public.material_reads
                    where student_id = p_student and read_on > current_date - 60) x),
    'exams',     (select coalesce(jsonb_agg(jsonb_build_object('level', level, 'score', score, 'passed', passed, 'at', created_at) order by created_at desc), '[]')
                    from (select * from public.exam_attempts where student_id = p_student order by created_at desc limit 10) e),
    'progress',  (select coalesce(jsonb_agg(jsonb_build_object('status', status, 'note', note, 'at', created_at) order by created_at desc), '[]')
                    from (select * from public.progress where student_id = p_student order by created_at desc limit 10) g)
  ) into v;
  return v;
end $$;

-- ----- chat -----
-- the conversations the signed-in person can see, newest first, with unread counts
create or replace function public.chat_inbox()
returns table (student_id uuid, student_name text, club text, last_body text, last_sender text,
               last_at timestamptz, unread bigint)
language sql stable security definer set search_path = public as $$
  with visible as (
    select p.id, p.full_name, p.club from public.profiles p
     where p.role = 'student' and (
           public.is_teacher() or p.id = auth.uid() or public.is_parent_of(p.id))
  )
  select v.id, v.full_name, v.club, last.body, last.sender_name, last.created_at,
         (select count(*) from public.messages m
           where m.student_id = v.id and m.sender_id <> auth.uid()
             and (public.is_teacher() or public.is_parent_of(v.id) or not m.private)
             and m.created_at > coalesce((select r.last_read_at from public.chat_reads r
                                           where r.user_id = auth.uid() and r.student_id = v.id), 'epoch'))
    from visible v
    left join lateral (
      select m.body, m.sender_name, m.created_at from public.messages m
       where m.student_id = v.id
         and (public.is_teacher() or public.is_parent_of(v.id) or not m.private)
       order by m.created_at desc limit 1) last on true
   order by last.created_at desc nulls last, v.full_name
   limit 300;
$$;

-- ----- certificates -----
create or replace function public.my_certificates(p_student uuid default null)
returns table (id text, full_name text, club text, level text, score int, issued_at timestamptz)
language sql stable security definer set search_path = public as $$
  select distinct on (a.level) a.id::text, p.full_name, a.club, a.level, a.score, a.created_at
    from public.exam_attempts a join public.profiles p on p.id = a.student_id
   where a.passed
     and a.student_id = coalesce(p_student, auth.uid())
     and (a.student_id = auth.uid() or public.is_teacher() or public.is_parent_of(a.student_id))
   order by a.level, a.score desc, a.created_at;
$$;

grant execute on function public.admin_list_users()                   to authenticated;
grant execute on function public.set_user_role(uuid, text, text)      to authenticated;
grant execute on function public.link_child(text)                     to authenticated;
grant execute on function public.student_report(uuid)                 to authenticated;
grant execute on function public.chat_inbox()                         to authenticated;
grant execute on function public.my_certificates(uuid)                to authenticated;
grant execute on function public.get_exam(text, text)                to authenticated;
grant execute on function public.submit_exam(text, text, jsonb)      to authenticated;
grant execute on function public.club_leaderboard(text, int)          to authenticated;
grant execute on function public.popular_materials(int)               to authenticated;

-- ---------------------------------------------------------------------
-- 6. Realtime — new books, announcements and chat messages appear live
-- ---------------------------------------------------------------------
do $$
begin
  begin alter publication supabase_realtime add table public.materials;     exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.notifications; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.messages;      exception when duplicate_object then null; end;
end $$;

-- =====================================================================
-- Make yourself the admin (run once, with YOUR e-mail):
--   update public.profiles set role = 'admin'
--    where id = (select id from auth.users where email = 'you@example.com');
-- =====================================================================
