-- =====================================================================
-- Code Cademy — Supabase backend
-- Paste this whole file into Supabase → SQL Editor → New query → Run.
-- It is safe to run more than once: every statement is idempotent.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. Tables
-- ---------------------------------------------------------------------
create table if not exists public.profiles (
  id          uuid primary key references auth.users(id) on delete cascade,
  full_name   text not null default '',
  role        text not null default 'student' check (role in ('student','teacher','admin')),
  club        text,
  created_at  timestamptz not null default now()
);

create table if not exists public.materials (
  id           bigint generated by default as identity primary key,
  club         text not null,
  level        text not null,
  title        text not null,
  file_path    text not null,
  uploaded_by  uuid references public.profiles(id) on delete set null,
  created_at   timestamptz not null default now()
);
-- extra columns used by the upgraded library (added safely on old databases)
alter table public.materials add column if not exists file_name text;
alter table public.materials add column if not exists file_size bigint;
alter table public.materials add column if not exists mime_type text;

create table if not exists public.exam_questions (
  id          bigint generated by default as identity primary key,
  club        text not null,
  level       text not null,
  question    text not null,
  option_a    text not null,   -- always the correct answer
  option_b    text not null,
  option_c    text not null,
  option_d    text not null,
  created_by  uuid references public.profiles(id) on delete set null,
  created_at  timestamptz not null default now()
);

create table if not exists public.exam_attempts (
  id          bigint generated by default as identity primary key,
  student_id  uuid not null references public.profiles(id) on delete cascade,
  club        text not null,
  level       text not null,
  score       int  not null,
  passed      boolean not null,
  created_at  timestamptz not null default now()
);

create table if not exists public.progress (
  id          bigint generated by default as identity primary key,
  student_id  uuid not null references public.profiles(id) on delete cascade,
  status      text,
  note        text,
  created_at  timestamptz not null default now()
);

create table if not exists public.notifications (
  id          bigint generated by default as identity primary key,
  club        text,            -- null = every club
  title       text not null,
  body        text not null,
  created_by  uuid references public.profiles(id) on delete set null,
  created_at  timestamptz not null default now()
);

-- NEW: every time a student opens a book we log it → streaks + leaderboard
create table if not exists public.material_reads (
  id           bigint generated by default as identity primary key,
  student_id   uuid not null references public.profiles(id) on delete cascade,
  material_id  bigint not null references public.materials(id) on delete cascade,
  club         text,
  read_on      date not null default current_date,
  created_at   timestamptz not null default now(),
  unique (student_id, material_id, read_on)
);

create index if not exists materials_club_level_idx on public.materials (club, level, created_at desc);
create index if not exists exam_q_club_level_idx    on public.exam_questions (club, level);
create index if not exists reads_student_idx        on public.material_reads (student_id, read_on desc);
create index if not exists reads_club_idx           on public.material_reads (club, read_on desc);

-- ---------------------------------------------------------------------
-- 2. Helpers
-- ---------------------------------------------------------------------
create or replace function public.is_teacher()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role in ('teacher','admin'));
$$;

create or replace function public.my_role()
returns text language sql stable security definer set search_path = public as $$
  select role from public.profiles where id = auth.uid();
$$;

create or replace function public.my_club()
returns text language sql stable security definer set search_path = public as $$
  select club from public.profiles where id = auth.uid();
$$;

-- Create the profile row automatically on sign-up (works even when
-- "Confirm email" is on and the browser has no session yet).
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, full_name, role, club)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', ''),
    case when new.raw_user_meta_data->>'role' = 'teacher' then 'teacher' else 'student' end,
    nullif(new.raw_user_meta_data->>'club', '')
  )
  on conflict (id) do nothing;
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------------
-- 3. Row Level Security
-- ---------------------------------------------------------------------
alter table public.profiles       enable row level security;
alter table public.materials      enable row level security;
alter table public.exam_questions enable row level security;
alter table public.exam_attempts  enable row level security;
alter table public.progress       enable row level security;
alter table public.notifications  enable row level security;
alter table public.material_reads enable row level security;

-- profiles
drop policy if exists "profiles: read own or teacher" on public.profiles;
create policy "profiles: read own or teacher" on public.profiles
  for select using (id = auth.uid() or public.is_teacher());
drop policy if exists "profiles: insert own" on public.profiles;
create policy "profiles: insert own" on public.profiles
  for insert with check (id = auth.uid());
drop policy if exists "profiles: update own" on public.profiles;
create policy "profiles: update own" on public.profiles
  for update using (id = auth.uid())
  with check (id = auth.uid() and role = public.my_role());  -- nobody can promote themselves

-- materials
drop policy if exists "materials: read club or teacher" on public.materials;
create policy "materials: read club or teacher" on public.materials
  for select using (public.is_teacher() or club = public.my_club());
drop policy if exists "materials: teacher insert" on public.materials;
create policy "materials: teacher insert" on public.materials
  for insert with check (public.is_teacher());
drop policy if exists "materials: teacher update" on public.materials;
create policy "materials: teacher update" on public.materials
  for update using (public.is_teacher());
drop policy if exists "materials: teacher delete" on public.materials;
create policy "materials: teacher delete" on public.materials
  for delete using (public.is_teacher());

-- exam questions: only teachers read them directly (students go through
-- get_exam(), which never reveals the correct answer)
drop policy if exists "exam_q: teacher all" on public.exam_questions;
create policy "exam_q: teacher all" on public.exam_questions
  for all using (public.is_teacher()) with check (public.is_teacher());

-- exam attempts: written only by submit_exam(); students read their own
drop policy if exists "attempts: read own or teacher" on public.exam_attempts;
create policy "attempts: read own or teacher" on public.exam_attempts
  for select using (student_id = auth.uid() or public.is_teacher());

-- progress
drop policy if exists "progress: read own or teacher" on public.progress;
create policy "progress: read own or teacher" on public.progress
  for select using (student_id = auth.uid() or public.is_teacher());
drop policy if exists "progress: teacher insert" on public.progress;
create policy "progress: teacher insert" on public.progress
  for insert with check (public.is_teacher());

-- notifications
drop policy if exists "notif: read" on public.notifications;
create policy "notif: read" on public.notifications
  for select using (public.is_teacher() or club is null or club = public.my_club());
drop policy if exists "notif: teacher insert" on public.notifications;
create policy "notif: teacher insert" on public.notifications
  for insert with check (public.is_teacher());

-- material reads
drop policy if exists "reads: read own or teacher" on public.material_reads;
create policy "reads: read own or teacher" on public.material_reads
  for select using (student_id = auth.uid() or public.is_teacher());
drop policy if exists "reads: insert own" on public.material_reads;
create policy "reads: insert own" on public.material_reads
  for insert with check (student_id = auth.uid());

-- ---------------------------------------------------------------------
-- 4. Storage bucket for books & materials
-- ---------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit)
values ('materials', 'materials', true, 52428800)  -- 50 MB per file
on conflict (id) do update set public = true, file_size_limit = excluded.file_size_limit;

drop policy if exists "materials bucket: public read"    on storage.objects;
create policy "materials bucket: public read" on storage.objects
  for select using (bucket_id = 'materials');
drop policy if exists "materials bucket: teacher upload" on storage.objects;
create policy "materials bucket: teacher upload" on storage.objects
  for insert to authenticated with check (bucket_id = 'materials' and public.is_teacher());
drop policy if exists "materials bucket: teacher update" on storage.objects;
create policy "materials bucket: teacher update" on storage.objects
  for update to authenticated using (bucket_id = 'materials' and public.is_teacher());
drop policy if exists "materials bucket: teacher delete" on storage.objects;
create policy "materials bucket: teacher delete" on storage.objects
  for delete to authenticated using (bucket_id = 'materials' and public.is_teacher());

-- ---------------------------------------------------------------------
-- 5. Server-side API (RPC functions called from the website)
-- ---------------------------------------------------------------------

-- Exam questions for a student, options shuffled, correct answer hidden.
create or replace function public.get_exam(p_club text, p_level text)
returns table (id bigint, question text, options text[])
language sql volatile security definer set search_path = public as $$
  select q.id, q.question,
         (select array_agg(o order by random())
            from unnest(array[q.option_a, q.option_b, q.option_c, q.option_d]) as o)
    from public.exam_questions q
   where q.club = p_club and q.level = p_level
     and (public.is_teacher() or p_club = public.my_club())
   order by q.created_at;
$$;

-- Grades the exam on the server and records the attempt.
-- p_answers = {"<question id>": "<chosen option text>", ...}
create or replace function public.submit_exam(p_club text, p_level text, p_answers jsonb)
returns table (score int, passed boolean, correct int, total int)
language plpgsql security definer set search_path = public as $$
declare
  v_total int; v_correct int; v_score int; v_passed boolean;
begin
  if auth.uid() is null then raise exception 'Not signed in'; end if;
  if p_club is distinct from public.my_club() then raise exception 'This exam is not for your club'; end if;

  select count(*), count(*) filter (where p_answers->>(q.id::text) = q.option_a)
    into v_total, v_correct
    from public.exam_questions q
   where q.club = p_club and q.level = p_level;

  if v_total = 0 then raise exception 'No questions for this level yet'; end if;

  v_score  := round(v_correct * 100.0 / v_total);
  v_passed := v_score >= 70;

  insert into public.exam_attempts (student_id, club, level, score, passed)
  values (auth.uid(), p_club, p_level, v_score, v_passed);

  return query select v_score, v_passed, v_correct, v_total;
end $$;

-- Top readers of a club over the last N days (names only — no emails).
-- p_club = null → every club (teachers).
create or replace function public.club_leaderboard(p_club text default null, p_days int default 7)
returns table (student_id uuid, full_name text, club text, books bigint, days_active bigint)
language sql stable security definer set search_path = public as $$
  select r.student_id, p.full_name, p.club,
         count(distinct r.material_id) as books,
         count(distinct r.read_on)     as days_active
    from public.material_reads r
    join public.profiles p on p.id = r.student_id
   where r.read_on >= current_date - greatest(p_days, 1) + 1
     and (case when public.is_teacher() then (p_club is null or p.club = p_club)
               else p.club = public.my_club() end)
   group by r.student_id, p.full_name, p.club
   order by books desc, days_active desc, p.full_name
   limit 10;
$$;

-- Most opened books (teacher insight).
create or replace function public.popular_materials(p_days int default 30)
returns table (material_id bigint, title text, club text, level text, readers bigint)
language sql stable security definer set search_path = public as $$
  select m.id, m.title, m.club, m.level, count(distinct r.student_id)
    from public.material_reads r
    join public.materials m on m.id = r.material_id
   where public.is_teacher()
     and r.read_on >= current_date - greatest(p_days, 1) + 1
   group by m.id
   order by 5 desc, m.title
   limit 5;
$$;

grant execute on function public.get_exam(text, text)                to authenticated;
grant execute on function public.submit_exam(text, text, jsonb)      to authenticated;
grant execute on function public.club_leaderboard(text, int)          to authenticated;
grant execute on function public.popular_materials(int)               to authenticated;

-- ---------------------------------------------------------------------
-- 6. Realtime — new books and announcements appear live in the dashboard
-- ---------------------------------------------------------------------
do $$
begin
  begin alter publication supabase_realtime add table public.materials;     exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.notifications; exception when duplicate_object then null; end;
end $$;
